### ISSUE TITLE
Failed to run action from typescript template

### ISSUE THREAD

**Issue by sergeyshevch** [github/local-action#72]
When I'm trying to run action using local-action i getting next error

```
/Users/MYPACKAGEPATH/node_modules/proxyquire/lib/proxyquire.js:307
    require.extensions[extension] = function (module, filename) {
                                  ^

TypeError: Cannot assign to read only property '.ts' of object '[object Object]'
    at /Users/MYPACKAGEPATH/node_modules/proxyquire/lib/proxyquire.js:307:35
    at Array.forEach (<anonymous>)
    at Proxyquire._overrideExtensionHandlers (/Users/MYPACKAGEPATH/node_modules/proxyquire/lib/proxyquire.js:300:35)
    at Proxyquire._withoutCache (/Users/MYPACKAGEPATH/node_modules/proxyquire/lib/proxyquire.js:218:39)
    at Proxyquire.load (/Users/MYPACKAGEPATH/node_modules/proxyquire/lib/proxyquire.js:129:15)
    at action (/Users/MYPACKAGEPATH/node_modules/@github/local-action/src/commands/run.ts:113:9)
    at Command.<anonymous> (/Users/MYPACKAGEPATH/node_modules/@github/local-action/src/command.ts:107:7)

Node.js v20.12.1
```

Local action installed in project as dev dependency. v1.5.1

**Comment by ncalteen** [comment]
Heyo! I'm sorry for the delay responding to this issue. I was running into a number of issues getting this package working with ESM and lost track of this problem.

I ended up removing proxyquire in favor of [quibble](https://github.com/testdouble/quibble), which seems to work out better with both CommonJS and ESM actions.

Can you try out v2.0.0 of this package and let me know if you see any issues?
